//! Map instruction custom error codes to Anchor's built-in [`ErrorCode`] values.
//!
//! `anchor_lang` does not expose `TryFrom<u32>` for [`ErrorCode`]; this module mirrors the
//! discriminants from `anchor_lang` 0.32.x `error.rs`.

use anchor_lang::error::ErrorCode;

pub(super) fn try_format_anchor_framework_error(code: u32) -> Option<String> {
    let ec: ErrorCode = match code {
        100 => ErrorCode::InstructionMissing,
        101 => ErrorCode::InstructionFallbackNotFound,
        102 => ErrorCode::InstructionDidNotDeserialize,
        103 => ErrorCode::InstructionDidNotSerialize,
        1000 => ErrorCode::IdlInstructionStub,
        1001 => ErrorCode::IdlInstructionInvalidProgram,
        1002 => ErrorCode::IdlAccountNotEmpty,
        1500 => ErrorCode::EventInstructionStub,
        2000 => ErrorCode::ConstraintMut,
        2001 => ErrorCode::ConstraintHasOne,
        2002 => ErrorCode::ConstraintSigner,
        2003 => ErrorCode::ConstraintRaw,
        2004 => ErrorCode::ConstraintOwner,
        2005 => ErrorCode::ConstraintRentExempt,
        2006 => ErrorCode::ConstraintSeeds,
        2007 => ErrorCode::ConstraintExecutable,
        2008 => ErrorCode::ConstraintState,
        2009 => ErrorCode::ConstraintAssociated,
        2010 => ErrorCode::ConstraintAssociatedInit,
        2011 => ErrorCode::ConstraintClose,
        2012 => ErrorCode::ConstraintAddress,
        2013 => ErrorCode::ConstraintZero,
        2014 => ErrorCode::ConstraintTokenMint,
        2015 => ErrorCode::ConstraintTokenOwner,
        2016 => ErrorCode::ConstraintMintMintAuthority,
        2017 => ErrorCode::ConstraintMintFreezeAuthority,
        2018 => ErrorCode::ConstraintMintDecimals,
        2019 => ErrorCode::ConstraintSpace,
        2020 => ErrorCode::ConstraintAccountIsNone,
        2021 => ErrorCode::ConstraintTokenTokenProgram,
        2022 => ErrorCode::ConstraintMintTokenProgram,
        2023 => ErrorCode::ConstraintAssociatedTokenTokenProgram,
        2024 => ErrorCode::ConstraintMintGroupPointerExtension,
        2025 => ErrorCode::ConstraintMintGroupPointerExtensionAuthority,
        2026 => ErrorCode::ConstraintMintGroupPointerExtensionGroupAddress,
        2027 => ErrorCode::ConstraintMintGroupMemberPointerExtension,
        2028 => ErrorCode::ConstraintMintGroupMemberPointerExtensionAuthority,
        2029 => ErrorCode::ConstraintMintGroupMemberPointerExtensionMemberAddress,
        2030 => ErrorCode::ConstraintMintMetadataPointerExtension,
        2031 => ErrorCode::ConstraintMintMetadataPointerExtensionAuthority,
        2032 => ErrorCode::ConstraintMintMetadataPointerExtensionMetadataAddress,
        2033 => ErrorCode::ConstraintMintCloseAuthorityExtension,
        2034 => ErrorCode::ConstraintMintCloseAuthorityExtensionAuthority,
        2035 => ErrorCode::ConstraintMintPermanentDelegateExtension,
        2036 => ErrorCode::ConstraintMintPermanentDelegateExtensionDelegate,
        2037 => ErrorCode::ConstraintMintTransferHookExtension,
        2038 => ErrorCode::ConstraintMintTransferHookExtensionAuthority,
        2039 => ErrorCode::ConstraintMintTransferHookExtensionProgramId,
        2500 => ErrorCode::RequireViolated,
        2501 => ErrorCode::RequireEqViolated,
        2502 => ErrorCode::RequireKeysEqViolated,
        2503 => ErrorCode::RequireNeqViolated,
        2504 => ErrorCode::RequireKeysNeqViolated,
        2505 => ErrorCode::RequireGtViolated,
        2506 => ErrorCode::RequireGteViolated,
        3000 => ErrorCode::AccountDiscriminatorAlreadySet,
        3001 => ErrorCode::AccountDiscriminatorNotFound,
        3002 => ErrorCode::AccountDiscriminatorMismatch,
        3003 => ErrorCode::AccountDidNotDeserialize,
        3004 => ErrorCode::AccountDidNotSerialize,
        3005 => ErrorCode::AccountNotEnoughKeys,
        3006 => ErrorCode::AccountNotMutable,
        3007 => ErrorCode::AccountOwnedByWrongProgram,
        3008 => ErrorCode::InvalidProgramId,
        3009 => ErrorCode::InvalidProgramExecutable,
        3010 => ErrorCode::AccountNotSigner,
        3011 => ErrorCode::AccountNotSystemOwned,
        3012 => ErrorCode::AccountNotInitialized,
        3013 => ErrorCode::AccountNotProgramData,
        3014 => ErrorCode::AccountNotAssociatedTokenAccount,
        3015 => ErrorCode::AccountSysvarMismatch,
        3016 => ErrorCode::AccountReallocExceedsLimit,
        3017 => ErrorCode::AccountDuplicateReallocs,
        4100 => ErrorCode::DeclaredProgramIdMismatch,
        4101 => ErrorCode::TryingToInitPayerAsProgramAccount,
        4102 => ErrorCode::InvalidNumericConversion,
        5000 => ErrorCode::Deprecated,
        _ => return None,
    };
    Some(format!("{}: {}", ec.name(), ec))
}
