[workspace]
resolver = "2"
members = [
    "cli",
    "decode",
    "glassbox",
    "hooks",
    "idl",
    "logger",
    "storage",
    "trace",
]

[workspace.package]
edition = "2021"
version = "1.1.1"
license = "MIT"

[workspace.dependencies]
hooks = { path = "hooks" }

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
    'cfg(target_os, values("solana"))',
    'cfg(feature, values("frozen-abi", "no-entrypoint"))',
]

# Clippy lint configuration that can not be applied in clippy.toml
[workspace.lints.clippy]
arithmetic_side_effects = "deny"
default_trait_access = "deny"
manual_let_else = "deny"
used_underscore_binding = "deny"

[patch.crates-io]
agave-feature-set = { git = "https://github.com/SeerApp/agave", branch = "patch-4.2.x" }
agave-reserved-account-keys = { git = "https://github.com/SeerApp/agave", branch = "patch-4.2.x" }
solana-syscalls = { git = "https://github.com/SeerApp/agave", branch = "patch-4.2.x" }
solana-bpf-loader-program = { git = "https://github.com/SeerApp/agave", branch = "patch-4.2.x" }
solana-builtins = { git = "https://github.com/SeerApp/agave", branch = "patch-4.2.x" }
solana-builtins-default-costs = { git = "https://github.com/SeerApp/agave", branch = "patch-4.2.x" }
solana-compute-budget = { git = "https://github.com/SeerApp/agave", branch = "patch-4.2.x" }
solana-compute-budget-instruction = { git = "https://github.com/SeerApp/agave", branch = "patch-4.2.x" }
solana-fee = { git = "https://github.com/SeerApp/agave", branch = "patch-4.2.x" }
solana-program-runtime = { git = "https://github.com/SeerApp/agave", branch = "patch-4.2.x" }
solana-rpc-client = { git = "https://github.com/SeerApp/agave", branch = "patch-4.2.x" }
solana-sbpf = { git = "https://github.com/SeerApp/sbpf", branch = "patch-0.21.1" }
solana-svm-callback = { git = "https://github.com/SeerApp/agave", branch = "patch-4.2.x" }
solana-svm-feature-set = { git = "https://github.com/SeerApp/agave", branch = "patch-4.2.x" }
solana-svm-log-collector = { git = "https://github.com/SeerApp/agave", branch = "patch-4.2.x" }
solana-svm-measure = { git = "https://github.com/SeerApp/agave", branch = "patch-4.2.x" }
solana-svm-timings = { git = "https://github.com/SeerApp/agave", branch = "patch-4.2.x" }
solana-svm-type-overrides = { git = "https://github.com/SeerApp/agave", branch = "patch-4.2.x" }
solana-system-program = { git = "https://github.com/SeerApp/agave", branch = "patch-4.2.x" }
solana-transaction-context = { git = "https://github.com/SeerApp/agave", branch = "patch-4.2.x" }
solana-transaction-status-client-types = { git = "https://github.com/SeerApp/agave", branch = "patch-4.2.x" }

[patch."https://github.com/SeerApp/seer"]
hooks = { path = "hooks" }
